name: .NET Core Desktop Workflow

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
        Solution_Name: ciLab.sln                        # Updated solution name
        Test_Project_Path: TestUnit1/TestUnit1.csproj  # Adjust to your actual test project path
        Wap_Project_Directory: UnitTestLab6           # Adjust as needed
        Wap_Project_Path: UnitTestLab6/UnitTestLab6.wapproj # Update as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x' # Replace with your required version

      - name: Restore dependencies
        run: dotnet restore ${{ env.Solution_Name }}

      - name: Build solution
        run: dotnet build ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }} --no-restore

      - name: Run tests
        run: dotnet test ${{ env.Test_Project_Path }} --configuration ${{ matrix.configuration }} --no-build --verbosity normal
